#!/usr/bin/env bash
#
# Summary: Show the global Any version
#
# Show the global Any version.

set -e
[ -n "$ANYENV_DEBUG" ] && set -x
cat << EOS
anyenv-global: **env global の結果を返すっぽいが後回し

EOS
exit


for env in $(anyenv-envs); do
  echo "$env: $($env global)"
done
