#!/usr/bin/env bash
# Summary: Configure the shell environment for anyenv
# Usage: eval "$(anyenv init - [<shell>])"

#--------------------
set -e
[ -n "$ANYENV_DEBUG" ] && set -x
#--------------------
cat << READING
anyenv-init: anyenv 環境を設定する

READING

#--------------------
print=""
no_rehash_arg=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash_arg="--no-rehash "
    shift
  fi
done
#--------------------
cat << READING
init の引数に
-           がある場合は print 変数に1を設定してシフト
--no-rehash がある場合は no_rehash_arg 変数に文字列を設定してシフト

READING


#--------------------
shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi
#--------------------
cat << READING
引数に設定することでシェルを指定することが可能？
\$shell=$shell

READING

#--------------------
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "anyenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}
#--------------------
cat << READING
anyenv と同様

READING

#--------------------
root="$(abs_dirname "$0")/.."
#--------------------
cat << READING
\$root=$root
\$print=$print
\${ANYENV_ROOT}=${ANYENV_ROOT}

READING

#--------------------
if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load anyenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and source (anyenv init -|psub)'
      ;;
    * )
      echo 'eval "$(anyenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi
#--------------------
cat << READING
anyenv init の後に - がない場合は、メッセージを表示して終了する

READING

#--------------------
mkdir -p "${ANYENV_ROOT}/envs"
#--------------------
cat << READING
envs ディレクトリを作成

READING

#--------------------
case "$shell" in
bash | zsh | fish )
  echo "source \"$root/completions/anyenv.${shell}\""
  ;;
esac
#--------------------
cat << READING
シェルが bash, zsh, fish の場合、メッセージを表示？？

READING

#--------------------
case "$shell" in
fish )
cat <<EOS
function anyenv
  set command \$argv[1]
  set -e argv[1]

  command anyenv "\$command" \$argv
end
EOS
  ;;
* )
cat <<EOS
anyenv() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi
  command anyenv "\$command" "\$@"
}
EOS
  ;;
esac
#--------------------
cat << READING
シェルに応じて、関数を表示？

READING
exit

# Print stderr to show caveat of initialization.
$(anyenv-install --list > /dev/null)

for env in $(anyenv-envs); do
  ENV_ROOT_VALUE=$(echo ${env}_ROOT | tr "[a-z]" "[A-Z]")
  ENV_ROOT="${ANYENV_ROOT}/envs/${env}"

  case "$shell" in
  fish )
    echo "set -gx ${ENV_ROOT_VALUE} \"${ENV_ROOT}\""
    export ${ENV_ROOT_VALUE}="${ENV_ROOT}"
    echo "set -gx PATH \$PATH \"${ENV_ROOT}/bin\""
    ;;
  * )
    echo "export ${ENV_ROOT_VALUE}=\"${ENV_ROOT}\""
    export ${ENV_ROOT_VALUE}="${ENV_ROOT}"
    echo "export PATH=\"${ENV_ROOT}/bin:\$PATH\""
    ;;
  esac

  if { ${ENV_ROOT}/bin/${env} commands | grep -q '^init$' ; } 2> /dev/null  ; then
    echo "$(${ENV_ROOT}/bin/${env} init - ${no_rehash_arg}${shell})"
  fi
done
